# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    displayName: 'Build job'

    steps: 
    - script: nosetests ./tests/test_app_endpoints.py
      displayName: 'Run tests'

    - script: docker image build . -t 'alexsuspis/demo-python-azure-app'
      displayName: 'Build docker image'

    - script: docker push 'alexsuspis/demo-python-azure-app' . -t 'alexsuspis/demo-python-azure-app'
      displayName: 'Push docker image to alexsuspis/ dockerhub repo'
